#!/usr/bin/env fish
# mise description="Compiles everything, with the proper env flags set"
# mise sources=["**/*.ts", "deno.json", "deno.lock"]
# mise outputs=["build/quickvid"]
# mise tools=["deno"]

deno compile --allow-sys=homedir --allow-run --allow-read --allow-write -o build/quickvid main.ts
