#!/usr/bin/env fish
#MISE description="Compiles everything, with the proper env flags set"
#MISE sources=["**/*.ts", "deno.json", "deno.lock"]
#MISE outputs=["build/quickvid"]
#MISE tools=["deno"]

deno compile --allow-sys=homedir --allow-run --allow-read --allow-write -o build/quickvid main.ts
