#!/usr/bin/env fish
#MISE description="Installs the tool and generates completions"
#MISE depends=["build"]
set program $MISE_PROJECT_ROOT/build/quickvid

echo (set_color green) "Installing binary"(set_color normal)
cp $program ~/.bin/quickvid
echo (set_color green) "Installing completions"(set_color normal)
mkdir -p ~/.local/share/fish/vendor_completions.d/
$program completions fish > ~/.local/share/fish/vendor_completions.d/quickvid.fish
